In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('adult.csv',names = list(range(0,15)))
df.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [16]:
df.columns = ['AGE','WORK_CLASS','FNLWGT','EDUCATION','EDUCATION_NUM',
             'MARITAL_STATUS','OCCU','RELATIONSHIP','RACE','SEX','CAPITAL_GAIN',
             'CAPITAL_LOSS','HOURS_PER_WEEK','NATIVE_COUNTRY','INCOME']
df.head()

AGE         WORK_CLASS  FNLWGT   EDUCATION  EDUCATION_NUM  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        MARITAL_STATUS                OCCU    RELATIONSHIP    RACE      SEX  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   CAPITAL_GAIN  CAPITAL_LOSS  HOURS_PER_WEEK  NATIVE_COUNTRY  INCOME  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [17]:
print(df.shape)

(32561, 15)


In [18]:
print(df.isnull().sum())

AGE               0
WORK_CLASS        0
FNLWGT            0
EDUCATION         0
EDUCATION_NUM     0
MARITAL_STATUS    0
OCCU              0
RELATIONSHIP      0
RACE              0
SEX               0
CAPITAL_GAIN      0
CAPITAL_LOSS      0
HOURS_PER_WEEK    0
NATIVE_COUNTRY    0
INCOME            0
dtype: int64


In [19]:
## so there are no null values

In [20]:
print(df.dtypes)

AGE                int64
WORK_CLASS        object
FNLWGT             int64
EDUCATION         object
EDUCATION_NUM      int64
MARITAL_STATUS    object
OCCU              object
RELATIONSHIP      object
RACE              object
SEX               object
CAPITAL_GAIN       int64
CAPITAL_LOSS       int64
HOURS_PER_WEEK     int64
NATIVE_COUNTRY    object
INCOME            object
dtype: object


In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
lb = LabelEncoder()

In [27]:
df['WORK_CLASS'] = lb.fit_transform(df['WORK_CLASS'])
df['EDUCATION'] = lb.fit_transform(df['EDUCATION'])
df['MARITAL_STATUS'] = lb.fit_transform(df['MARITAL_STATUS'])
df['OCCU'] = lb.fit_transform(df['OCCU'])
df['RELATIONSHIP'] = lb.fit_transform(df['RELATIONSHIP'])
df['RACE'] = lb.fit_transform(df['RACE'])
df['SEX'] = lb.fit_transform(df['SEX'])
df['NATIVE_COUNTRY'] = lb.fit_transform(df['NATIVE_COUNTRY'])
df['INCOME'] = lb.fit_transform(df['INCOME'])

In [28]:
df.dtypes

AGE               int64
WORK_CLASS        int64
FNLWGT            int64
EDUCATION         int64
EDUCATION_NUM     int64
MARITAL_STATUS    int64
OCCU              int64
RELATIONSHIP      int64
RACE              int64
SEX               int64
CAPITAL_GAIN      int64
CAPITAL_LOSS      int64
HOURS_PER_WEEK    int64
NATIVE_COUNTRY    int64
INCOME            int32
dtype: object

In [29]:
df.head()

AGE  WORK_CLASS  FNLWGT  EDUCATION  EDUCATION_NUM  MARITAL_STATUS  OCCU  \
0   39           7   77516          9             13               4     1   
1   50           6   83311          9             13               2     4   
2   38           4  215646         11              9               0     6   
3   53           4  234721          1              7               2     6   
4   28           4  338409          9             13               2    10   

   RELATIONSHIP  RACE  SEX  CAPITAL_GAIN  CAPITAL_LOSS  HOURS_PER_WEEK  \
0             1     4    1          2174             0              40   
1             0     4    1             0             0              13   
2             1     4    1             0             0              40   
3             0     2    1             0             0              40   
4             5     2    0             0             0              40   

   NATIVE_COUNTRY  INCOME  
0              39       0  
1              39       0  
2              39       0  
3              39       0  
4               5       0

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)

(32561, 14)
(32561,)


In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(24420, 14)
(8141, 14)
(24420,)
(8141,)


In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [43]:
def model_sc(m) : 
    print("Training Score : ",m.score(x_train,y_train))
    print("Testing Score : ",m.score(x_test,y_test))
def model_met(y_test,ypred_m) :
    cm = confusion_matrix(y_test,ypred_m)
    print(cm)
    print("Classification Report : ",classification_report(y_test,ypred_m))

In [44]:
m1 = DecisionTreeClassifier(criterion = 'entropy',max_depth = 9,min_samples_split = 40)
m1.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=9, min_samples_split=40)

In [45]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[0 1 0 ... 0 1 0]


In [46]:
## 0 means <=50K
## 1 means >50k
model_sc(m1)

Training Score :  0.8622850122850123
Testing Score :  0.8480530647340622


In [47]:
model_met(y_test,ypred_m1)

[[5830  362]
 [ 875 1074]]
Classification Report :                precision    recall  f1-score   support

           0       0.87      0.94      0.90      6192
           1       0.75      0.55      0.63      1949

    accuracy                           0.85      8141
   macro avg       0.81      0.75      0.77      8141
weighted avg       0.84      0.85      0.84      8141



In [48]:
## TP = 5830 , FN = 362 , FP = 875, TN = 1074
## PRECISION = TP/(TP+FP) OR TN/(TN+FN)
## Recall = TP/(TP+FN) OR TN/(TN+FP)
## F1-score = ((2*Precision*Recall)/(Precission+Recall))
## Accuracy = ((TP+TN)/(TP+FN+FP+TN))

In [50]:
pre0 = 5830/(5830+875)
pre1 = 1074/(1074+362)
print(pre0)
print(pre1)

0.8695003728560775
0.7479108635097493


In [51]:
rec0 = 5830/(5830+362)
rec1 = 1074/(1074+875)
print(rec0)
print(rec1)

0.9415374677002584
0.5510518214468958


In [61]:
f10 = ((2*pre0*rec0)/(pre0+rec0))
f11 = ((2*pre1*rec1)/(pre1+rec1))
print(f10)
print(f11)

0.9040862216019229
0.6345642540620383


In [53]:
accu = (5830+1074)/(5830+362+875+1074)
print(accu)

0.8480530647340622


In [88]:
per_miss_class_m1 = ((362+875)/(5830+362+875+1074))
print("Percentage Missclassification of m1 : ",per_miss_class_m1)

Percentage Missclassification of m1 :  0.15194693526593783


In [56]:
m2 = RandomForestClassifier(criterion = 'entropy',max_depth = 9,min_samples_split = 35,n_estimators = 60)
m2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=9, min_samples_split=35,
                       n_estimators=60)

In [57]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[0 1 0 ... 0 1 0]


In [58]:
model_sc(m2)

Training Score :  0.8621212121212121
Testing Score :  0.8537034762314212


In [59]:
model_met(y_test,ypred_m2)

[[5896  296]
 [ 895 1054]]
Classification Report :                precision    recall  f1-score   support

           0       0.87      0.95      0.91      6192
           1       0.78      0.54      0.64      1949

    accuracy                           0.85      8141
   macro avg       0.82      0.75      0.77      8141
weighted avg       0.85      0.85      0.84      8141



In [60]:
## TP = 5896 , FN = 296 , FP = 895, TN = 1054
## PRECISION = TP/(TP+FP) OR TN/(TN+FN)
## Recall = TP/(TP+FN) OR TN/(TN+FP)
## F1-score = ((2*Precision*Recall)/(Precission+Recall))
## Accuracy = ((TP+TN)/(TP+FN+FP+TN))

In [63]:
pre0_m2 = 5896/(5896+895)
pre1_m2 = 1054/(1054+296)
print(pre0_m2)
print(pre1_m2)
rec0_m2 = 5896/(5896+296)
rec1_m2 = 1054/(1054+895)
print(rec0_m2)
print(rec1_m2)
f10_m2 = ((2*pre0_m2*rec0_m2)/(pre0_m2+rec0_m2))
f11_m2 = ((2*pre1_m2*rec1_m2)/(pre1_m2+rec1_m2))
print(f10_m2)
print(f11_m2)
accu = (5896+1054)/(5896+296+895+1054)
print(accu)

0.8682079222500368
0.7807407407407407
0.9521963824289406
0.5407901487942535
0.9082646537780174
0.638981509548348
0.8537034762314212


In [89]:
per_miss_class_m2 = (895+296)/(5896+296+895+1054)
print("Percentage Missclassification for model2 : ",per_miss_class_m2)

Percentage Missclassification for model2 :  0.1462965237685788


In [64]:
m3 = LogisticRegression()
m3.fit(x_train,y_train)

LogisticRegression()

In [65]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[0 0 0 ... 0 0 0]


In [66]:
model_sc(m3)

Training Score :  0.8001638001638002
Testing Score :  0.8003930721041641


In [67]:
model_met(y_test,ypred_m3)

[[6001  191]
 [1434  515]]
Classification Report :                precision    recall  f1-score   support

           0       0.81      0.97      0.88      6192
           1       0.73      0.26      0.39      1949

    accuracy                           0.80      8141
   macro avg       0.77      0.62      0.63      8141
weighted avg       0.79      0.80      0.76      8141



In [ ]:
## TP = 6001 , FN = 191 , FP = 1434, TN = 515
## PRECISION = TP/(TP+FP) OR TN/(TN+FN)
## Recall = TP/(TP+FN) OR TN/(TN+FP)
## F1-score = ((2*Precision*Recall)/(Precission+Recall))
## Accuracy = ((TP+TN)/(TP+FN+FP+TN))

In [69]:
pre0_m3 = 6001/(6001+1434)
pre1_m3 = 515/(515+191)
print(pre0_m3)
print(pre1_m3)
rec0_m3 = 6001/(6001+191)
rec1_m3 = 515/(515+1434)
print(rec0_m3)
print(rec1_m3)
f10_m3 = ((2*pre0_m3*rec0_m3)/(pre0_m3+rec0_m3))
f11_m3 = ((2*pre1_m3*rec1_m3)/(pre1_m3+rec1_m3))
print(f10_m3)
print(f11_m3)
accu = (6001+515)/(6001+191+1434+515)
print(accu)

0.807128446536651
0.7294617563739377
0.9691537467700259
0.2642380708055413
0.880751449328539
0.3879472693032015
0.8003930721041641


In [90]:
per_miss_class_m3 = (191+1434)/(6001+191+1434+515)
print("Percentage Missclassification for model3 : ",per_miss_class_m3)

Percentage Missclassification for model3 :  0.1996069278958359


In [71]:
m4 = KNeighborsClassifier(n_neighbors = 180)
m4.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=180)

In [72]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[0 0 0 ... 0 0 0]


In [73]:
model_sc(m4)

Training Score :  0.7765356265356266
Testing Score :  0.7773000859845228


In [75]:
model_met(y_test,ypred_m4)

[[6191    1]
 [1812  137]]
Classification Report :                precision    recall  f1-score   support

           0       0.77      1.00      0.87      6192
           1       0.99      0.07      0.13      1949

    accuracy                           0.78      8141
   macro avg       0.88      0.54      0.50      8141
weighted avg       0.83      0.78      0.69      8141



In [77]:
## TP = 6191 , FN = 1 , FP = 1812, TN = 137
## PRECISION = TP/(TP+FP) OR TN/(TN+FN)
## Recall = TP/(TP+FN) OR TN/(TN+FP)
## F1-score = ((2*Precision*Recall)/(Precission+Recall))
## Accuracy = ((TP+TN)/(TP+FN+FP+TN))

In [79]:
pre0_m4 = 6191/(6191+1812)
pre1_m4 = 137/(137+1)
print(pre0_m4)
print(pre1_m4)
rec0_m4 = 6191/(6191+1)
rec1_m4 = 137/(137+1812)
print(rec0_m4)
print(rec1_m4)
f10_m4 = ((2*pre0_m4*rec0_m4)/(pre0_m4+rec0_m4))
f11_m4 = ((2*pre1_m4*rec1_m4)/(pre1_m4+rec1_m4))
print(f10_m4)
print(f11_m4)
accu = (6191+137)/(6191+1+1812+137)
print(accu)

0.7735849056603774
0.9927536231884058
0.9998385012919897
0.07029245767060031
0.872278971468827
0.13128893148059417
0.7773000859845228


In [91]:
per_miss_class_m4 = (1812+1)/(6191+1+1812+137)
print("Percentage Missclassification for model4 : ",per_miss_class_m2)

Percentage Missclassification for model4 :  0.1996069278958359


In [80]:
m5 = SVC(kernel = 'linear',C = 1)
m5.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [82]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[0 0 0 ... 0 0 0]


In [83]:
model_sc(m5)

Training Score :  0.7954954954954955
Testing Score :  0.7968308561601769


In [84]:
model_met(y_test,ypred_m5)

[[5891  301]
 [1353  596]]
Classification Report :                precision    recall  f1-score   support

           0       0.81      0.95      0.88      6192
           1       0.66      0.31      0.42      1949

    accuracy                           0.80      8141
   macro avg       0.74      0.63      0.65      8141
weighted avg       0.78      0.80      0.77      8141



In [81]:
## TP = 5891 , FN = 301 , FP = 1353, TN = 596
## PRECISION = TP/(TP+FP) OR TN/(TN+FN)
## Recall = TP/(TP+FN) OR TN/(TN+FP)
## F1-score = ((2*Precision*Recall)/(Precission+Recall))
## Accuracy = ((TP+TN)/(TP+FN+FP+TN))

In [86]:
pre0_m5 = 5891/(5891+1353)
pre1_m5 = 596/(596+301)
print(pre0_m5)
print(pre1_m5)
rec0_m5 = 5891/(5891+301)
rec1_m5 = 596/(596+1353)
print(rec0_m5)
print(rec1_m5)
f10_m5 = ((2*pre0_m5*rec0_m5)/(pre0_m5+rec0_m5))
f11_m5 = ((2*pre1_m5*rec1_m5)/(pre1_m5+rec1_m5))
print(f10_m5)
print(f11_m5)
accu = (5891+596)/(5891+301+1353+596)
print(accu)

0.8132247377139702
0.6644370122630993
0.9513888888888888
0.30579784504874297
0.8768978862756772
0.41883345045678144
0.7968308561601769


In [92]:
per_miss_class_m5 = (1353+301)/(5891+301+1353+596)
print("Percentage Missclassification for model5 : ",per_miss_class_m5)

Percentage Missclassification for model5 :  0.20316914383982312


In [93]:
## Best model with accuracy score = Random Forest Classifier(accu = 0.8537)